<template>
  <div class="page-shell">
    <header class="page-header"><p class="eyebrow">{{dashboard?.role || 'Your'}} workspace</p><h1>Welcome, {{dashboard?.username}}.</h1><p>{{intro}}</p></header>
    <p v-if="error" class="error-state">{{error}}</p>
    <div v-else-if="!dashboard" class="empty-state">Loading your workspace…</div>
    <template v-else>
      <section v-if="progress" class="metrics"><article class="glass-card"><b>{{progress.totalXp}}</b><span>Mastery XP</span></article><article class="glass-card"><b>{{progress.masteredSkills}}</b><span>Skills mastered</span></article><article class="glass-card"><b>{{progress.proficientSkills}}</b><span>Skills proficient</span></article></section>
      <section class="dashboard-grid">
        <article class="glass-card panel"><div class="panel-title"><h2>Classes</h2><span class="status">{{dashboard.classes.length}}</span></div><div v-if="!dashboard.classes.length" class="empty-state">No classes yet.</div><div v-for="room in dashboard.classes" :key="room.id" class="list-row"><div><b>{{room.name}}</b><p>Grade {{room.grade}} · {{room.teacher}}</p></div><span>{{room.students.length}} learners</span></div></article>
        <article class="glass-card panel"><div class="panel-title"><h2>Announcements</h2><span class="status">Latest</span></div><div v-if="!dashboard.announcements.length" class="empty-state">Nothing new.</div><div v-for="item in dashboard.announcements" :key="item.id" class="list-row"><div><b>{{item.title}}</b><p>{{item.body}}</p></div><small>{{item.className}}</small></div></article>
        <article v-if="dashboard.role==='STUDENT'" class="glass-card panel"><div class="panel-title"><h2>Assignments</h2><router-link to="/assignments">View all</router-link></div><div v-for="item in dashboard.assignments" :key="item.id" class="list-row"><div><b>{{item.title}}</b><p>{{item.className}}</p></div><span class="status">{{item.completed?`${item.score}/${item.total}`:'Ready'}}</span></div></article>
        <article v-if="dashboard.learners.length" class="glass-card panel"><div class="panel-title"><h2>Learner progress</h2><span class="status">Private</span></div><div v-for="learner in dashboard.learners" :key="learner.username" class="list-row"><div><b>{{learner.username}}</b><p>{{learner.masteredSkills}} mastered · {{learner.proficientSkills}} proficient</p></div><strong>{{learner.totalXp}} XP</strong></div></article>
      </section>
      <section v-if="dashboard.role==='TEACHER'" class="teacher-tools glass-card"><h2>Teacher quick actions</h2><div class="tool-grid"><form @submit.prevent="addClass"><h3>Create class</h3><div class="form-field"><label>Name<input v-model="classForm.name" required></label></div><div class="form-field"><label>Grade<select v-model.number="classForm.grade"><option v-for="g in [3,4,5,6]" :key="g">{{g}}</option></select></label></div><button class="button primary">Create</button></form><form v-if="dashboard.classes[0]" @submit.prevent="addAnnouncement"><h3>Post announcement</h3><div class="form-field"><label>Title<input v-model="newsForm.title" required></label></div><div class="form-field"><label>Message<textarea v-model="newsForm.body" required></textarea></label></div><button class="button primary">Publish</button></form></div></section>
      <section v-if="dashboard.role==='TEACHER'&&dashboard.classes[0]" class="teacher-tools glass-card"><h2>Build the classroom</h2><div class="tool-grid"><form @submit.prevent="addStudent"><h3>Create student account</h3><div class="form-field"><label>Username<input v-model="studentForm.username" required></label></div><div class="form-field"><label>First name<input v-model="studentForm.firstName" required></label></div><div class="form-field"><label>Last name<input v-model="studentForm.lastName" required></label></div><div class="form-field"><label>Email<input v-model="studentForm.email" type="email" required></label></div><button class="button primary">Create learner</button><p v-if="temporaryPassword" class="success">Temporary password: <strong>{{temporaryPassword}}</strong></p></form><form @submit.prevent="addAssignment"><h3>Create assignment</h3><div class="form-field"><label>Title<input v-model="assignmentForm.title" required></label></div><div class="form-field"><label>Description<input v-model="assignmentForm.description" required></label></div><div class="form-field"><label>Skill<select v-model="assignmentForm.skillCodes[0]"><option v-for="skill in allSkills" :key="skill.code" :value="skill.code">{{skill.title}}</option></select></label></div><div class="form-field"><label>Questions<select v-model.number="assignmentForm.questionCount"><option v-for="n in [3,5,10]" :key="n">{{n}}</option></select></label></div><button class="button primary">Publish assignment</button></form></div></section>
      <section v-if="dashboard.role==='ADMIN'" class="teacher-tools glass-card"><h2>User and role management</h2><div class="tool-grid"><div><div v-for="user in users" :key="user.id" class="list-row"><div><b>{{user.username}}</b><p>{{user.first_name}} {{user.last_name}}</p></div><span>{{user.roles.map(role=>role.name.replace('ROLE_','')).join(', ')}}</span></div></div><form @submit.prevent="addRole"><h3>Add a role</h3><div class="form-field"><label>Username<input v-model="roleForm.username" required></label></div><div class="form-field"><label>Role<select v-model="roleForm.roleName"><option v-for="role in ['ROLE_STUDENT','ROLE_TEACHER','ROLE_PARENT','ROLE_ADMIN']" :key="role">{{role}}</option></select></label></div><button class="button primary">Update role</button></form></div></section>
    </template>
  </div>
</template>
<script>
import {api} from '../api'
export default{name:'Dashboard',data:()=>({dashboard:null,progress:null,courses:[],users:[],error:'',temporaryPassword:'',classForm:{name:'',grade:4},newsForm:{title:'',body:''},studentForm:{username:'',firstName:'',lastName:'',email:''},assignmentForm:{title:'',description:'',skillCodes:['g4-multi-digit-addition'],questionCount:5,dueAt:null},roleForm:{username:'',roleName:'ROLE_STUDENT'}}),computed:{intro(){return{STUDENT:'Choose the next small step in your learning path.',TEACHER:'Guide classes, assignments, and progress from one place.',PARENT:'Follow linked learners without changing their work.',ADMIN:'Review the learning platform and its classrooms.'}[this.dashboard?.role]||'Your Math Practice overview.'},allSkills(){return this.courses.flatMap(c=>c.units.flatMap(u=>u.skills))}},async created(){document.title='Dashboard · Math Practice';await this.load()},methods:{async load(){try{this.dashboard=await api('/api/dashboard');if(this.dashboard.role==='STUDENT')this.progress=await api('/api/progress/me');if(this.dashboard.role==='TEACHER')this.courses=await api('/api/courses');if(this.dashboard.role==='ADMIN')this.users=await api('/api/users')}catch(e){this.error=e.message}},async addClass(){await api('/api/classes',{method:'POST',body:JSON.stringify(this.classForm)});this.classForm={name:'',grade:4};await this.load()},async addAnnouncement(){await api(`/api/classes/${this.dashboard.classes[0].id}/announcements`,{method:'POST',body:JSON.stringify(this.newsForm)});this.newsForm={title:'',body:''};await this.load()},async addStudent(){try{const created=await api(`/api/classes/${this.dashboard.classes[0].id}/students`,{method:'POST',body:JSON.stringify(this.studentForm)});this.temporaryPassword=created.temporaryPassword;this.studentForm={username:'',firstName:'',lastName:'',email:''};await this.load()}catch(e){this.error=e.message}},async addAssignment(){try{await api(`/api/classes/${this.dashboard.classes[0].id}/assignments`,{method:'POST',body:JSON.stringify(this.assignmentForm)});this.assignmentForm={title:'',description:'',skillCodes:['g4-multi-digit-addition'],questionCount:5,dueAt:null};await this.load()}catch(e){this.error=e.message}},async addRole(){try{await api('/api/role/addToUser',{method:'POST',body:JSON.stringify(this.roleForm)});this.roleForm={username:'',roleName:'ROLE_STUDENT'};await this.load()}catch(e){this.error=e.message}}}}
</script>
<style scoped>.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-bottom:1.25rem}.metrics article{padding:1.4rem;display:grid}.metrics b{font:800 2.2rem var(--ff-serif);color:hsl(var(--clr-accent-200))}.metrics span{color:hsl(var(--clr-white-600))}.dashboard-grid{display:grid;grid-template-columns:1fr 1fr;gap:1.25rem}.panel{padding:1.5rem}.panel-title,.list-row{display:flex;justify-content:space-between;gap:1rem;align-items:flex-start}.panel-title{align-items:center;margin-bottom:1rem}.panel-title h2,.teacher-tools h2{font:700 1.6rem var(--ff-serif)}.panel-title a{color:hsl(var(--clr-accent-200))}.list-row{padding:1rem 0;border-top:1px solid hsl(var(--clr-white-200)/.1)}.list-row p,.list-row small,.list-row>span{color:hsl(var(--clr-white-600));font-size:.85rem}.teacher-tools{padding:1.5rem;margin:1.25rem 0 2rem}.teacher-tools:last-child{margin-bottom:4rem}.tool-grid{display:grid;grid-template-columns:1fr 1fr;gap:2rem;margin-top:1rem}.tool-grid form{display:grid;gap:1rem}.success{padding:1rem;border-radius:1rem;background:hsl(var(--clr-accent-400)/.12);color:hsl(var(--clr-accent-200))}@media(max-width:45rem){.metrics,.dashboard-grid,.tool-grid{grid-template-columns:1fr}}</style>
