create table if not exists role (
    id integer generated by default as identity primary key,
    name varchar(255) not null unique
);

create table if not exists app_user (
    id integer generated by default as identity primary key,
    username varchar(255) not null unique,
    password varchar(255) not null,
    email varchar(255),
    first_name varchar(255),
    last_name varchar(255)
);

create table if not exists app_user_roles (
    user_id integer not null references app_user(id),
    roles_id integer not null references role(id),
    primary key (user_id, roles_id)
);

create table if not exists question (
    id integer generated by default as identity primary key,
    question varchar(255),
    subject varchar(255),
    difficulty integer,
    answer1 varchar(255),
    answer2 varchar(255),
    answer3 varchar(255),
    answer4 varchar(255),
    correct_answer integer
);

create table if not exists experience (
    id integer generated by default as identity primary key,
    current_exp integer,
    exp_per_level integer,
    level integer,
    user_id integer unique references app_user(id)
);

create table if not exists experience_questions (
    experience_id integer not null references experience(id),
    questions_id integer not null references question(id),
    primary key (experience_id, questions_id)
);

create table if not exists user_question (
    id integer generated by default as identity primary key,
    question_id integer unique references question(id),
    user_id integer references app_user(id),
    date_time timestamp,
    answered_correct boolean not null default false
);

create table if not exists message (
    id integer generated by default as identity primary key,
    message varchar(255)
);

create table if not exists learning_course (
    id integer generated by default as identity primary key,
    grade_level integer not null,
    slug varchar(80) not null unique,
    title varchar(120) not null,
    description varchar(500) not null,
    sort_order integer not null
);

create table if not exists learning_unit (
    id integer generated by default as identity primary key,
    course_id integer not null references learning_course(id) on delete cascade,
    title varchar(120) not null,
    description varchar(500) not null,
    sort_order integer not null
);

create table if not exists learning_skill (
    id integer generated by default as identity primary key,
    unit_id integer not null references learning_unit(id) on delete cascade,
    code varchar(80) not null unique,
    title varchar(120) not null,
    introduction varchar(1000) not null,
    worked_example varchar(1000) not null,
    hint_text varchar(1000) not null,
    explanation varchar(1000) not null,
    generator_type varchar(40) not null,
    difficulty integer not null default 1,
    sort_order integer not null
);

create table if not exists classroom (
    id integer generated by default as identity primary key,
    name varchar(120) not null,
    grade_level integer not null,
    teacher_id integer not null references app_user(id)
);

create table if not exists classroom_enrollment (
    classroom_id integer not null references classroom(id) on delete cascade,
    student_id integer not null references app_user(id) on delete cascade,
    primary key (classroom_id, student_id)
);

create table if not exists parent_student (
    parent_id integer not null references app_user(id) on delete cascade,
    student_id integer not null references app_user(id) on delete cascade,
    primary key (parent_id, student_id)
);

create table if not exists announcement (
    id integer generated by default as identity primary key,
    classroom_id integer not null references classroom(id) on delete cascade,
    author_id integer not null references app_user(id),
    title varchar(160) not null,
    body varchar(2000) not null,
    published_at timestamp not null default current_timestamp
);

create table if not exists assessment (
    id integer generated by default as identity primary key,
    creator_id integer not null references app_user(id),
    title varchar(160) not null,
    description varchar(500) not null,
    published boolean not null default false
);

create table if not exists assessment_question (
    id integer generated by default as identity primary key,
    assessment_id integer not null references assessment(id) on delete cascade,
    skill_id integer references learning_skill(id),
    prompt varchar(500) not null,
    answer_a varchar(255) not null,
    answer_b varchar(255) not null,
    answer_c varchar(255) not null,
    answer_d varchar(255) not null,
    correct_answer varchar(255) not null,
    hint_text varchar(500),
    explanation varchar(1000),
    sort_order integer not null
);

create table if not exists assignment (
    id integer generated by default as identity primary key,
    classroom_id integer not null references classroom(id) on delete cascade,
    assessment_id integer not null references assessment(id),
    due_at timestamp,
    assigned_at timestamp not null default current_timestamp,
    unique (classroom_id, assessment_id)
);

create table if not exists assignment_submission (
    id integer generated by default as identity primary key,
    assignment_id integer not null references assignment(id),
    student_id integer not null references app_user(id),
    score integer not null,
    total integer not null,
    answers varchar(4000) not null,
    completed_at timestamp not null default current_timestamp,
    unique (assignment_id, student_id)
);

create table if not exists practice_session (
    id integer generated by default as identity primary key,
    student_id integer not null references app_user(id),
    mode varchar(20) not null,
    status varchar(20) not null,
    created_at timestamp not null default current_timestamp,
    completed_at timestamp
);

create table if not exists practice_question (
    id integer generated by default as identity primary key,
    session_id integer not null references practice_session(id) on delete cascade,
    skill_id integer not null references learning_skill(id),
    prompt varchar(500) not null,
    answer_a varchar(255) not null,
    answer_b varchar(255) not null,
    answer_c varchar(255) not null,
    answer_d varchar(255) not null,
    correct_answer varchar(255) not null,
    selected_answer varchar(255),
    answered_correct boolean,
    sort_order integer not null
);

create table if not exists skill_mastery (
    student_id integer not null references app_user(id) on delete cascade,
    skill_id integer not null references learning_skill(id) on delete cascade,
    attempts integer not null default 0,
    correct_answers integer not null default 0,
    sessions_completed integer not null default 0,
    status varchar(20) not null default 'NOT_STARTED',
    xp integer not null default 0,
    updated_at timestamp not null default current_timestamp,
    primary key (student_id, skill_id)
);

create index if not exists idx_unit_course on learning_unit(course_id);
create index if not exists idx_skill_unit on learning_skill(unit_id);
create index if not exists idx_enrollment_student on classroom_enrollment(student_id);
create index if not exists idx_practice_student on practice_session(student_id);
